# apiVersion: v1
# kind: Secret
# metadata:
#   name: app-secrets
# type: Opaque
# data:
#   NODE_ENV: cHJvZHVjdGlvbmFs # Base64 encoded value for "production"

apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  NODE_ENV: cHJvZHVjdGlvbg== # Base64 encoded value for "production"