---
# tasks file for roles/nginx
- name: Install Nginx
  apt:
    name: nginx
    state: present
- name: Copy index.html file
  template:
    src:  index.html.j2
    dest: /var/www/html/index.html
  notify: Restart Nginx
