pipeline {

    agent any

    tools {
        maven 'Maven-3.9.8'
    }
    
    stages {
        stage('Build') {
            steps {
                echo "Building the Java application on branch ${BRANCH_NAME}"
                sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...'
            }
        }
    }
    post {
        success {
            echo 'Build and test succeeded!'
        }
        failure {
            echo 'Build or test failed!'
        }
    }
}
