---
arch_mapping:  
  x86_64: amd64
  aarch64: arm64
docker_pkgs:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
req_pkgs:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - software-properties-common