---
# tasks file for roles/mysql
- name: Install MySQL server
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"

- name: Ensure MySQL service is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create MySQL user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    host: '%'
    state: present

- name: Create MySQL database
  mysql_db:
    name: "{{ db_name }}"
    state: present