---
- hosts: all
  tasks:
    # - name: Task to Install Nginx
    #   ansible.builtin.apt:
    #     name: nginx
    #     state: present
    # - name: Print hostname
    #   debug:
    #     msg: "{{inventory_hostname}}"
    - name:
      copy: 
        src: index.j2
        dest: /var/www/html/index.html