---
- hosts: all
  tasks:
    - name: Task to Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
    - name: Print hostname
      debug:
        msg: "{{inventory_hostname}}"
    - name:
      template: 
        src: index.j2
        dest: /var/www/html/index.html
      notify:
        - Restart Nginx
  handlers:
    - name: Restart Nginx
      ansible.builtin.service: 
        name: nginx
        start: restarted