route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'admin'
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'
  - name: admin
    slack_configs:
    - channel: "#random"
      api_url: "https://hooks.slack.com/services/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"
  # - name: admin
  #   email_configs:
  #   - to: 'shivmodi258@gmail.com'
  #     from: 'shivmodi258@gmail.com'
  #     smarthost: smtp.gmail.com:587
  #     auth_username: 'testlabuserdemo@gmail.com'
  #     auth_identity: 'testlabuserdemo@gmail.com'
  #     auth_password: 'Password_1234'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
  



# route:
#   receiver: admin

# receivers:
#   - name: admin
#     slack_configs:
#     - channel: "#random"
#       api_url: "https://hooks.slack.com/services/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"
 