plugin: aws_ec2
regions:
  - ap-southeast-1
filters:
  instance-state-name:
    - running
  tag:Name: shiv-instance-*
hostnames:
  - dns-name
compose:
  ansible_host: public_dns_name
  ansible_private_key_file: shiv-key-terraform-test.pem
  ansible_user: ubuntu
groups:
  master: "'master' in tags.Name"
  worker: "'worker' in tags.Name"